@startuml

(*) -> "Login"

if "Any Trustlets?" then
  -->[yes] "Show Trustlets list"
  if "Deploy trustlet?" then
    -->[yes] "Deploy Trustlet"
  else
    -->[no] if "Register trustlet?" then
      -->[yes] "Register Trustlet"
    else
      -->[no] if "Delete trustlet?" then
        ->[yes] "Delete Trustlet"
      else
        -->[no] (*)
      endif
    endif
  endif
else
  ->[no] "Register Trustlet"
endif

"Register Trustlet" --> "Show Trustlets list"
"Deploy Trustlet" --> "Show Trustlets list"
"Delete Trustlet" --> "Show Trustlets list"

@enduml
